//! NTSC signal chain renderer.
//!
//! Converts Apple II video memory reads into ABGR pixel output.
//!
//! Internal pixel format: ABGR8888 stored as a native-endian `u32`.
//! On little-endian (x86/ARM) the in-memory byte order is `[R, G, B, A]`,
//! which matches egui's `ColorImage::from_rgba_unmultiplied` directly.
//! This avoids a per-frame channel-swap pass in the GUI layer.
//!
//! Hi-res colour uses a proper NTSC signal model ported from `source/NTSC.cpp`.

use apple2_core::bus::MemMode;
use crate::framebuffer::{Framebuffer, FB_WIDTH};

// ── Lo-res 16-colour ABGR palette ─────────────────────────────────────────────

/// Standard Apple II lo-res colour palette (ABGR8888, alpha = 0xFF).
/// R is in the low byte so that `pixels_as_bytes()` yields RGBA byte order.
const LORES_PALETTE: [u32; 16] = [
    0xFF000000, // 0: Black
    0xFF12129D, // 1: Deep Red
    0xFF990011, // 2: Dark Blue
    0xFFBB22AA, // 3: Purple
    0xFF226600, // 4: Dark Green
    0xFF6A6A6A, // 5: Dark Gray
    0xFFFF2222, // 6: Medium Blue
    0xFFEE9955, // 7: Light Blue
    0xFF004466, // 8: Brown
    0xFF0066FF, // 9: Orange
    0xFF999999, // A: Light Gray
    0xFFAA99FF, // B: Pink
    0xFF11DD11, // C: Light Green
    0xFF00FFFF, // D: Yellow
    0xFFAAFF33, // E: Aqua
    0xFFFFFFFF, // F: White
];

// ── NTSC colour tables ────────────────────────────────────────────────────────

/// Pre-computed NTSC colour lookup tables matching AppleWin's `g_aHueColorTV`.
///
/// 4 phases × 4096 12-bit sequences.  Generated by `NtscTables::generate()` using
/// the same IIR filter parameters as AppleWin's `initChromaPhaseTables()`.
struct NtscTables {
    /// `hue_color_tv[phase][signal_bits_12]` → ARGB colour.
    hue_color_tv: Box<[[u32; 4096]; 4]>,
    /// Pre-expanded pixel-double mask: source byte (0–127) → 14-bit pattern.
    pixel_double_mask: [u16; 128],
}

impl NtscTables {
    fn generate() -> Self {
        // ── IIR filter state (static across the full generation loop) ──────────
        // These match the C++ static local variables in initFilterSignal etc.
        let mut sig_x = [0.0f64; 3];
        let mut sig_y = [0.0f64; 3];
        let mut chr_x = [0.0f64; 3];
        let mut chr_y = [0.0f64; 3];
        let mut lum0_x = [0.0f64; 3];
        let mut lum0_y = [0.0f64; 3];
        let mut lum1_x = [0.0f64; 3];
        let mut lum1_y = [0.0f64; 3];

        // Filter parameters from NTSC.cpp
        const SIG_GAIN: f64  = 7.614490548;
        const SIG_A: f64     = -0.2718798058;
        const SIG_B: f64     =  0.7465656072;

        const CHR_GAIN: f64  = 7.438011255;
        const CHR_A: f64     = -0.7318893645;
        const CHR_B: f64     =  1.2336442711;

        const LUM_GAIN: f64  = 13.71331570;
        const LUM_A: f64     = -0.3961075449;
        const LUM_B: f64     =  1.1044202472;

        // YIQ → RGB coefficients
        const I_TO_R: f64 =  0.956;
        const I_TO_G: f64 = -0.272;
        const I_TO_B: f64 = -1.105;
        const Q_TO_R: f64 =  0.621;
        const Q_TO_G: f64 = -0.647;
        const Q_TO_B: f64 =  1.702;

        const RAD_45: f64 = std::f64::consts::PI * 0.25;
        const RAD_90: f64 = std::f64::consts::PI * 0.5;
        // CYCLESTART = DEG_TO_RAD(45) = PI/4 = RAD_45
        const CYCLESTART: f64 = RAD_45;

        let clamp01 = |x: f64| -> f64 { x.clamp(0.0, 1.0) };

        // Inline filter helpers (modify filter state, return y[2])
        macro_rules! filter_signal {
            ($z:expr) => {{
                sig_x[0] = sig_x[1]; sig_x[1] = sig_x[2]; sig_x[2] = $z / SIG_GAIN;
                sig_y[0] = sig_y[1]; sig_y[1] = sig_y[2];
                sig_y[2] = sig_x[0] + sig_x[2] + 2.0 * sig_x[1]
                         + SIG_A * sig_y[0] + SIG_B * sig_y[1];
                sig_y[2]
            }};
        }
        macro_rules! filter_chroma {
            ($z:expr) => {{
                chr_x[0] = chr_x[1]; chr_x[1] = chr_x[2]; chr_x[2] = $z / CHR_GAIN;
                chr_y[0] = chr_y[1]; chr_y[1] = chr_y[2];
                // Note: −x[0] (inverted), no 2·x[1] term — matches initFilterChroma
                chr_y[2] = -chr_x[0] + chr_x[2]
                         + CHR_A * chr_y[0] + CHR_B * chr_y[1];
                chr_y[2]
            }};
        }
        macro_rules! filter_luma0 {
            ($z:expr) => {{
                lum0_x[0] = lum0_x[1]; lum0_x[1] = lum0_x[2]; lum0_x[2] = $z / LUM_GAIN;
                lum0_y[0] = lum0_y[1]; lum0_y[1] = lum0_y[2];
                lum0_y[2] = lum0_x[0] + lum0_x[2] + 2.0 * lum0_x[1]
                          + LUM_A * lum0_y[0] + LUM_B * lum0_y[1];
                lum0_y[2]
            }};
        }
        macro_rules! filter_luma1 {
            ($z:expr) => {{
                lum1_x[0] = lum1_x[1]; lum1_x[1] = lum1_x[2]; lum1_x[2] = $z / LUM_GAIN;
                lum1_y[0] = lum1_y[1]; lum1_y[1] = lum1_y[2];
                lum1_y[2] = lum1_x[0] + lum1_x[2] + 2.0 * lum1_x[1]
                          + LUM_A * lum1_y[0] + LUM_B * lum1_y[1];
                lum1_y[2]
            }};
        }

        let mut hue_color_tv = Box::new([[0u32; 4096]; 4]);

        for phase in 0..4usize {
            // phi is reset once per phase (like the C++ outer loop), then accumulates.
            // Since each sequence advances phi by 24 * PI/4 = 6*PI = 3 full cycles,
            // phi returns to the same modular value for every sequence in a phase.
            let mut phi = (phase as f64 * RAD_90) + CYCLESTART;

            for s in 0..4096usize {
                let mut t = s as u32;
                // Per-sequence local vars (reset each sequence)
                let mut _y0  = 0.0f64;
                let mut y1   = 0.0f64;
                let mut _c   = 0.0f64;
                let mut iq_i = 0.0f64;
                let mut iq_q = 0.0f64;
                let mut _z   = 0.0f64;

                // Process 12 bits of `s`, each doubled to 2 samples (14MHz oversampling)
                for _n in 0..12 {
                    _z = if t & 0x800 != 0 { 1.0 } else { 0.0 };
                    t <<= 1;

                    for _k in 0..2 {
                        let zz = filter_signal!(_z);
                        _c     = filter_chroma!(zz);
                        _y0    = filter_luma0!(zz);
                        y1     = filter_luma1!(zz - _c);

                        let c2 = _c * 2.0;
                        iq_i += (c2 * phi.cos() - iq_i) / 8.0;
                        iq_q += (c2 * phi.sin() - iq_q) / 8.0;

                        phi += RAD_45;
                    }
                }

                // Compute RGB using the ColorTV (y1 luma) path
                let color_idx = s & 15;
                let (r, g, b) = if color_idx == 0 {
                    // NTSC_REMOVE_BLACK_GHOSTING
                    (0.0, 0.0, 0.0)
                } else if color_idx == 15 {
                    // NTSC_REMOVE_WHITE_RINGING
                    (1.0, 1.0, 1.0)
                } else if color_idx == 5 {
                    // NTSC_REMOVE_GRAY_CHROMA (Gray1)
                    let g = 0x83_u32 as f64 / 255.0;
                    (g, g, g)
                } else if color_idx == 10 {
                    // NTSC_REMOVE_GRAY_CHROMA (Gray2)
                    let g = 0x78_u32 as f64 / 255.0;
                    (g, g, g)
                } else {
                    let r = clamp01(y1 + I_TO_R * iq_i + Q_TO_R * iq_q);
                    let g = clamp01(y1 + I_TO_G * iq_i + Q_TO_G * iq_q);
                    let b = clamp01(y1 + I_TO_B * iq_i + Q_TO_B * iq_q);
                    (r, g, b)
                };

                // Store as ABGR: R in low byte, B in bits 16-23.
                // On little-endian the in-memory bytes are [R, G, B, A] = RGBA,
                // which egui's from_rgba_unmultiplied() can consume directly.
                hue_color_tv[phase][s] = 0xFF000000
                    | (((b * 255.0) as u32) << 16)
                    | (((g * 255.0) as u32) << 8)
                    |   ((r * 255.0) as u32);
            }
        }

        // Build pixel-double mask: each source bit k → output bits 2k and 2k+1
        let mut pixel_double_mask = [0u16; 128];
        for byte in 0u8..128 {
            let mut mask = 0u16;
            for b in 0..7u16 {
                if byte & (1 << b) != 0 {
                    mask |= 3 << (b * 2);
                }
            }
            pixel_double_mask[byte as usize] = mask;
        }

        NtscTables { hue_color_tv, pixel_double_mask }
    }
}

// ── CharRom ───────────────────────────────────────────────────────────────────

/// Apple II character ROM (7×8 bit font, 128 characters × 8 rows × 7 pixels).
/// Actual ROM bytes should be loaded from firmware at startup.
/// This stub uses a blank ROM.
pub struct CharRom {
    data: Vec<u8>,
}

impl CharRom {
    pub fn new(data: Vec<u8>) -> Self {
        Self { data }
    }

    /// Return the 8 rows of pixels for `ch` (0–127).
    #[inline]
    pub fn glyph(&self, ch: u8) -> [u8; 8] {
        let idx = (ch as usize & 0x7F) * 8;
        if idx + 8 <= self.data.len() {
            self.data[idx..idx + 8].try_into().unwrap_or([0u8; 8])
        } else {
            [0u8; 8]
        }
    }
}

// ── NtscRenderer ─────────────────────────────────────────────────────────────

/// NTSC video renderer state.
pub struct NtscRenderer {
    char_rom: CharRom,
    /// Pre-computed NTSC colour lookup tables.
    ntsc_tables: NtscTables,
    /// Whether to apply CRT half-scanline darkening after each frame.
    pub scanlines: bool,
    /// Monochrome tint `[R, G, B]`.  `None` = normal colour output.
    /// Set from `Config::mono_tint()` whenever video settings change.
    pub mono_tint: Option<[u8; 3]>,
    /// Blend adjacent pixel rows for colour smoothing
    /// (matches AppleWin VS_COLOR_VERTICAL_BLEND).
    pub color_vertical_blend: bool,
}

impl NtscRenderer {
    pub fn new(char_rom: CharRom, scanlines: bool) -> Self {
        Self {
            char_rom,
            ntsc_tables: NtscTables::generate(),
            scanlines,
            mono_tint: None,
            color_vertical_blend: false,
        }
    }

    // ── Public dispatch ───────────────────────────────────────────────────────

    /// Render one complete video frame into `fb`.
    ///
    /// `frame_no` is used to compute the flash state (toggles every 16 frames,
    /// matching AppleWin's `g_nVideoFlashCounter` at 60 Hz ≈ 1.8 Hz blink rate).
    ///
    /// Inspects `mode` to select text, lo-res, or hi-res rendering, including
    /// mixed-mode overlays.  Every mode covers the full 560×384 framebuffer, so
    /// no explicit clear is needed — each pixel is initialised by the render path.
    pub fn render(
        &self,
        main_ram: &[u8; 65536],
        aux_ram:  &[u8; 65536],
        mode: MemMode,
        frame_no: u32,
        fb: &mut Framebuffer,
    ) {

        // Flash state: toggles every 16 frames (~3.75 Hz at 60 fps).
        let flash_on = (frame_no / 16).is_multiple_of(2);

        let page2    = mode.contains(MemMode::MF_PAGE2);
        let graphics = mode.contains(MemMode::MF_GRAPHICS);
        let hires    = mode.contains(MemMode::MF_HIRES);
        let mixed    = mode.contains(MemMode::MF_MIXED);
        let vid80    = mode.contains(MemMode::MF_VID80);
        let dhires   = mode.contains(MemMode::MF_DHIRES);

        let text_base: usize = if page2 { 0x0800 } else { 0x0400 };
        let text_page = &main_ram[text_base..text_base + 0x400];

        if !graphics {
            // Text mode
            if vid80 {
                self.render_text80_rows(main_ram, aux_ram, text_base, 0, 24, flash_on, fb);
            } else {
                self.render_text40_rows(text_page, 0, 24, flash_on, fb);
            }
        } else if hires {
            let hgr_base: usize = if page2 { 0x4000 } else { 0x2000 };
            let scan_lines = if mixed { 160 } else { 192 };
            if dhires && vid80 {
                // Double hi-res: 560×192 with 16-color NTSC artifact palette
                self.render_dhires(main_ram, aux_ram, hgr_base, scan_lines, fb);
            } else {
                // Standard hi-res graphics with proper NTSC signal model
                self.render_hires(main_ram, hgr_base, scan_lines, fb);
            }
            if mixed {
                if vid80 {
                    self.render_text80_rows(main_ram, aux_ram, text_base, 20, 24, flash_on, fb);
                } else {
                    self.render_text40_rows(text_page, 20, 24, flash_on, fb);
                }
            }
        } else {
            // Lo-res graphics
            self.render_lores(text_page, fb);
            if mixed {
                // Overwrite the last 4 text rows with actual text glyphs
                if vid80 {
                    self.render_text80_rows(main_ram, aux_ram, text_base, 20, 24, flash_on, fb);
                } else {
                    self.render_text40_rows(text_page, 20, 24, flash_on, fb);
                }
            }
        }

        // Colour vertical blend: average each pair of rendered rows.
        // Applied before scanlines so the blend operates on full-brightness data.
        if self.color_vertical_blend {
            apply_color_vertical_blend(fb);
        }

        // Monochrome tint: desaturate then apply phosphor colour.
        if let Some([tr, tg, tb]) = self.mono_tint {
            apply_mono_tint(fb, tr, tg, tb);
        }

        // CRT scanline darkening: dim every odd fb row (the "in-between" line)
        // to simulate the dark gaps between CRT scan lines, matching AppleWin's
        // default half-scanline mode.
        if self.scanlines {
            apply_scanlines(fb);
        }
    }

    // ── Text rendering ────────────────────────────────────────────────────────

    /// Render the full 40×24 text screen.
    pub fn render_text40(&self, text_page: &[u8], flash_on: bool, fb: &mut Framebuffer) {
        self.render_text40_rows(text_page, 0, 24, flash_on, fb);
    }

    /// Render text rows `row_start..row_end` (exclusive) from `text_page`.
    ///
    /// Apple II text byte encoding:
    ///   $00–$3F → INVERSE  (black pixels on white background)
    ///   $40–$7F → FLASH    (alternates between normal and inverse based on `flash_on`)
    ///   $80–$FF → NORMAL   (white pixels on black background)
    pub fn render_text40_rows(
        &self,
        text_page: &[u8],
        row_start: usize,
        row_end: usize,
        flash_on: bool,
        fb: &mut Framebuffer,
    ) {
        let pixels = fb.pixels_mut();
        for row in row_start..row_end {
            for col in 0..40usize {
                let addr = text_addr(row, col);
                let ch   = text_page.get(addr).copied().unwrap_or(0xA0); // $A0 = normal space

                // Determine display mode and glyph index from byte value.
                // The glyph index is always bits 5-0 of the byte (ch & 0x3F gives
                // the shape; the extra bit selects upper/lower glyph bank).
                let (fg, bg, glyph_idx) = if ch < 0x40 {
                    // INVERSE: bits 0-5 select the glyph (same shapes as $80-$BF)
                    (0xFF000000u32, 0xFFFFFFFFu32, ch & 0x3F)
                } else if ch < 0x80 {
                    // FLASH: same glyphs but alternates normal/inverse
                    if flash_on {
                        (0xFFFFFFFFu32, 0xFF000000u32, ch & 0x3F)
                    } else {
                        (0xFF000000u32, 0xFFFFFFFFu32, ch & 0x3F)
                    }
                } else {
                    // NORMAL: bit 6 selects upper/lower glyph bank → strip bit 7
                    (0xFFFFFFFFu32, 0xFF000000u32, ch & 0x7F)
                };

                let glyph  = self.char_rom.glyph(glyph_idx);
                let base_x = col * 14;
                let base_y = row * 16;
                for (gy, &bits) in glyph.iter().enumerate() {
                    // Pre-compute the two framebuffer row offsets for this glyph row.
                    // Each glyph row doubles vertically (gy*2 and gy*2+1).
                    let row0 = (base_y + gy * 2)     * FB_WIDTH;
                    let row1 = (base_y + gy * 2 + 1) * FB_WIDTH;
                    for gx in 0..7usize {
                        let on   = bits & (0x80u8 >> gx) != 0;
                        let argb = if on { fg } else { bg };
                        // Each glyph pixel → 2×2 block; write all 4 directly.
                        let px = base_x + gx * 2;
                        pixels[row0 + px]     = argb;
                        pixels[row0 + px + 1] = argb;
                        pixels[row1 + px]     = argb;
                        pixels[row1 + px + 1] = argb;
                    }
                }
            }
        }
    }

    /// Render 80-column text rows `row_start..row_end` (exclusive).
    ///
    /// Apple //e 80-column layout: columns alternate between aux and main RAM.
    ///   screen col 0  → aux RAM  at `text_addr(row, 0)`
    ///   screen col 1  → main RAM at `text_addr(row, 0)`
    ///   screen col 2  → aux RAM  at `text_addr(row, 1)`
    ///   screen col 3  → main RAM at `text_addr(row, 1)` … and so on.
    ///
    /// Each character occupies 7 px × 16 px on the 560×384 framebuffer
    /// (1 px per glyph dot horizontally, 2 px per glyph dot vertically).
    #[allow(clippy::too_many_arguments)]
    pub fn render_text80_rows(
        &self,
        main_ram:  &[u8; 65536],
        aux_ram:   &[u8; 65536],
        text_base: usize,
        row_start: usize,
        row_end:   usize,
        flash_on:  bool,
        fb:        &mut Framebuffer,
    ) {
        let main_page = &main_ram[text_base..text_base + 0x400];
        let aux_page  = &aux_ram [text_base..text_base + 0x400];

        for row in row_start..row_end {
            // Acquire once per text row — not 80× per column.
            let pixels = fb.pixels_mut();
            let base_y = row * 16;
            for screen_col in 0..80usize {
                let phys_col = screen_col / 2;
                // Even screen columns → aux RAM; odd → main RAM
                let ch = if screen_col & 1 == 0 {
                    aux_page.get(text_addr(row, phys_col)).copied().unwrap_or(0xA0)
                } else {
                    main_page.get(text_addr(row, phys_col)).copied().unwrap_or(0xA0)
                };

                let (fg, bg, glyph_idx) = if ch < 0x40 {
                    (0xFF000000u32, 0xFFFFFFFFu32, ch & 0x3F)
                } else if ch < 0x80 {
                    if flash_on {
                        (0xFFFFFFFFu32, 0xFF000000u32, ch & 0x3F)
                    } else {
                        (0xFF000000u32, 0xFFFFFFFFu32, ch & 0x3F)
                    }
                } else {
                    (0xFFFFFFFFu32, 0xFF000000u32, ch & 0x7F)
                };

                let glyph  = self.char_rom.glyph(glyph_idx);
                // 80-col: 7 px per column (no horizontal pixel doubling)
                let base_x = screen_col * 7;
                for (gy, &bits) in glyph.iter().enumerate() {
                    let row0 = (base_y + gy * 2)     * FB_WIDTH;
                    let row1 = (base_y + gy * 2 + 1) * FB_WIDTH;
                    for gx in 0..7usize {
                        let on   = bits & (0x80u8 >> gx) != 0;
                        let argb = if on { fg } else { bg };
                        // 1 × 2 block per glyph pixel (vertical doubling only)
                        pixels[row0 + base_x + gx] = argb;
                        pixels[row1 + base_x + gx] = argb;
                    }
                }
            }
        }
    }

    // ── Lo-res graphics ───────────────────────────────────────────────────────

    /// Render a full lo-res screen from `text_page` (same 960-byte layout as text mode).
    ///
    /// Each byte encodes two colour blocks: low nibble = top 8 px, high nibble = bottom 8 px.
    /// Each cell is 14×16 px (same as text characters).
    pub fn render_lores(&self, text_page: &[u8], fb: &mut Framebuffer) {
        let pixels = fb.pixels_mut();
        for row in 0..24usize {
            for col in 0..40usize {
                let addr     = text_addr(row, col);
                let byte     = text_page.get(addr).copied().unwrap_or(0);
                let lo_color = (byte & 0x0F) as usize; // top half
                let hi_color = ((byte >> 4) & 0x0F) as usize; // bottom half
                let base_x   = col * 14;
                let base_y   = row * 16;

                // Fill each of the 8 top rows as a 14-pixel horizontal slice.
                let top_argb = LORES_PALETTE[lo_color];
                for dy in 0..8usize {
                    let start = (base_y + dy) * FB_WIDTH + base_x;
                    pixels[start..start + 14].fill(top_argb);
                }
                // Fill each of the 8 bottom rows.
                let bot_argb = LORES_PALETTE[hi_color];
                for dy in 8..16usize {
                    let start = (base_y + dy) * FB_WIDTH + base_x;
                    pixels[start..start + 14].fill(bot_argb);
                }
            }
        }
    }

    // ── Double hi-res graphics ────────────────────────────────────────────────

    /// Render `scan_lines` double hi-res scan lines using alternating aux/main RAM.
    ///
    /// Apple II DHIRES: 560 actual pixels per row.  Each scan line assembles bits from
    /// 40 aux bytes and 40 main bytes, interleaved as 7-bit groups:
    ///   aux[0] bits 0-6 → pixels 0-6
    ///   main[0] bits 0-6 → pixels 7-13
    ///   aux[1] bits 0-6 → pixels 14-20 … and so on.
    ///
    /// Colour decoding: consecutive groups of 4 bits map to one of the 16 lo-res colours
    /// (same NTSC artifact palette).  Each colour group spans 4 screen pixels.
    /// 560 / 4 = 140 colour groups per row.
    pub fn render_dhires(
        &self,
        main_ram:  &[u8; 65536],
        aux_ram:   &[u8; 65536],
        hgr_base:  usize,
        scan_lines: usize,
        fb:        &mut Framebuffer,
    ) {
        for y in 0..scan_lines {
            // Non-linear Apple II hi-res address layout (same as standard hi-res)
            let row_offset = (y & 7) * 0x0400
                + ((y >> 3) & 7) * 0x0080
                + (y >> 6) * 0x0028;

            // Pack 560 dhires bits into 9 u64 words (72 bytes vs 560 bytes for [bool;560]).
            // Each source byte-pair contributes 14 bits: 7 from aux then 7 from main.
            let mut packed = [0u64; 9];
            for bx in 0..40usize {
                let addr = hgr_base + row_offset + bx;
                let ab = aux_ram.get(addr).copied().unwrap_or(0) as u64 & 0x7F;
                let mb = main_ram.get(addr).copied().unwrap_or(0) as u64 & 0x7F;
                let word = ab | (mb << 7); // 14 bits
                let bit_base = bx * 14;
                let wi = bit_base / 64;
                let bi = bit_base % 64;
                packed[wi] |= word << bi;
                if bi + 14 > 64 {
                    packed[wi + 1] |= word >> (64 - bi);
                }
            }

            // Decode 140 four-bit colour groups from the packed bitfield → LORES_PALETTE
            let py = y * 2;
            let row0 = py       * FB_WIDTH;
            let row1 = (py + 1) * FB_WIDTH;
            let pixels = fb.pixels_mut();
            for xi in 0..140usize {
                let bit_pos = xi * 4;
                let wi = bit_pos / 64;
                let bi = bit_pos % 64;
                let color = if bi + 4 <= 64 {
                    ((packed[wi] >> bi) & 0xF) as usize
                } else {
                    let lo = packed[wi] >> bi;
                    let hi = packed[wi + 1] << (64 - bi);
                    ((lo | hi) & 0xF) as usize
                };
                let argb    = LORES_PALETTE[color];
                let base_px = xi * 4;
                pixels[row0 + base_px..row0 + base_px + 4].fill(argb);
                pixels[row1 + base_px..row1 + base_px + 4].fill(argb);
            }
        }
    }

    // ── Hi-res graphics ───────────────────────────────────────────────────────

    /// Render `scan_lines` hi-res scan lines using the full NTSC signal chain.
    ///
    /// Matches AppleWin's `updateScreenSingleHires40` → `updatePixels` →
    /// `updatePixelHueColorTVSingleScanline` path (VT_COLOR_TV, colour-burst on).
    ///
    /// For each scanline:
    ///  1. Reset phase=0, signal_shift_register=0, last_col_pixel=0
    ///     (matches `updateVideoScannerAddress()` resetting g_nColorPhaseNTSC etc.)
    ///  2. For each source byte, build a 14-bit pixel-doubled signal.
    ///     If hi-bit is set, shift by 1 (half-dot shift) and use the previous
    ///     byte's carry bit for the new low bit.
    ///  3. Feed the 14 bits LSB-first into the 12-bit shift register.
    ///     Look up the colour for each pixel from the NTSC table indexed by
    ///     the current (phase, shift_register) pair.
    ///  4. Write the colour to both framebuffer rows 2y and 2y+1.
    pub fn render_hires(
        &self,
        main_ram: &[u8; 65536],
        hgr_base: usize,
        scan_lines: usize,
        fb: &mut Framebuffer,
    ) {
        let tables = &self.ntsc_tables.hue_color_tv;
        let pdm    = &self.ntsc_tables.pixel_double_mask;

        for y in 0..scan_lines {
            // Non-linear Apple II hi-res address layout
            let row_offset = (y & 7) * 0x0400
                + ((y >> 3) & 7) * 0x0080
                + (y >> 6) * 0x0028;

            // Reset NTSC state at the start of each scanline
            // (matches updateVideoScannerAddress: g_nColorPhaseNTSC = 0,
            //  g_nLastColumnPixelNTSC = 0, g_nSignalBitsNTSC = 0)
            let mut phase:       usize = 0;
            let mut signal_bits: usize = 0;
            let mut last_col:    u32   = 0; // g_nLastColumnPixelNTSC

            let py = y * 2;
            let mut px = 0usize;

            // Hoist mutable pixel slice and constant row offsets outside the byte loop.
            // Previously these were reacquired on every byte (40× per scanline).
            let pixels = fb.pixels_mut();
            let row0 = py       * FB_WIDTH;
            let row1 = (py + 1) * FB_WIDTH;

            for bx in 0..40usize {
                let addr = hgr_base + row_offset + bx;
                let byte = main_ram.get(addr).copied().unwrap_or(0);

                // Pixel-double the 7 source bits to a 14-bit pattern.
                // g_aPixelDoubleMaskHGR[m & 0x7F]: bit k → output bits 2k, 2k+1.
                let bits7  = (byte & 0x7F) as usize;
                let mut bits14 = pdm[bits7] as u32;

                // Hi-bit half-dot shift: shift all 14 bits left by 1 and fill
                // bit 0 with the carry from the previous byte.
                // g_nLastColumnPixelNTSC is always bit 13 of the un-shifted bits14
                // (= second copy of source bit 6), regardless of hi-bit.
                if byte & 0x80 != 0 {
                    bits14 = (bits14 << 1) | last_col;
                }
                // Carry for next byte = bit 13 of the pixel-double mask (before shift)
                // = (byte & 0x40) >> 6  (source bit 6, the MSB of the 7 data bits)
                last_col = ((byte >> 6) & 1) as u32;

                // Feed 14 bits LSB-first into the NTSC signal chain.
                for bit_idx in 0..14u32 {
                    let bit = (bits14 >> bit_idx) & 1;
                    signal_bits = ((signal_bits << 1) | bit as usize) & 0xFFF;
                    let color = tables[phase][signal_bits];
                    pixels[row0 + px] = color;
                    pixels[row1 + px] = color;
                    px += 1;
                    phase = (phase + 1) & 3;
                }
            }
        }
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/// Apple II text/lo-res page address (non-linear layout, relative to page base).
#[inline]
fn text_addr(row: usize, col: usize) -> usize {
    (row % 8) * 0x80 + (row / 8) * 0x28 + col
}

/// Blend each pair of adjacent rendered rows (colour vertical blend).
///
/// Each Apple II scanline k renders to 2 identical FB rows (2k and 2k+1).
/// Approximates AppleWin's updateFramebufferTVSingleScanline inbetween-row
/// calculation: odd row = 50% of (row above + row below).
fn apply_color_vertical_blend(fb: &mut Framebuffer) {
    use crate::framebuffer::{FB_WIDTH, FB_HEIGHT};
    let pixels = fb.pixels_mut();
    let mut y = 1usize;
    while y + 1 < FB_HEIGHT {
        for x in 0..FB_WIDTH {
            let above = pixels[(y - 1) * FB_WIDTH + x];
            let below = pixels[(y + 1) * FB_WIDTH + x];
            let blended = ((above & 0xFEFEFEFE) >> 1).wrapping_add((below & 0xFEFEFEFE) >> 1);
            pixels[y * FB_WIDTH + x] = blended | 0xFF000000;
        }
        y += 2;
    }
}

/// Convert every framebuffer pixel to a monochrome tinted value.
///
/// Computes BT.601 luminance Y from the RGB pixel, then scales the
/// phosphor tint colour by Y/255 to produce a bright-to-dark gradient
/// in the tint colour rather than pure grey.
///
/// Pixel format is ABGR: R in bits 7-0, G in bits 15-8, B in bits 23-16,
/// A in bits 31-24.
fn apply_mono_tint(fb: &mut Framebuffer, tr: u8, tg: u8, tb: u8) {
    for pixel in fb.pixels_mut().iter_mut() {
        let r =  *pixel        & 0xFF; // R in low byte (ABGR format)
        let g = (*pixel >>  8) & 0xFF;
        let b = (*pixel >> 16) & 0xFF;
        // BT.601 luma (integer, 0–255)
        let y = (r * 299 + g * 587 + b * 114) / 1000;
        let nr = (tr as u32 * y / 255) as u8;
        let ng = (tg as u32 * y / 255) as u8;
        let nb = (tb as u32 * y / 255) as u8;
        *pixel = 0xFF000000 | ((nb as u32) << 16) | ((ng as u32) << 8) | nr as u32;
    }
}

/// Simulate CRT scanline gaps (half-scanlines mode).
///
/// Dims every odd framebuffer row to 50% brightness, matching a CRT's dark
/// gaps between phosphor lines.
fn apply_scanlines(fb: &mut Framebuffer) {
    use crate::framebuffer::{FB_WIDTH, FB_HEIGHT};
    let pixels = fb.pixels_mut();
    for y in (1..FB_HEIGHT).step_by(2) {
        let row = &mut pixels[y * FB_WIDTH..(y + 1) * FB_WIDTH];
        for px in row.iter_mut() {
            // Halve R, G, B in one pass: mask off the MSB of each byte to
            // prevent carry between channels, then right-shift.  Alpha byte
            // (0xFF in bits 31-24) keeps the sign bit set so it stays 0x7F
            // after >> 1; OR back 0xFF000000 to restore it.
            // This is format-agnostic across ARGB and ABGR.
            *px = 0xFF000000 | ((*px & 0x00FEFEFE) >> 1);
        }
    }
}
